### ISSUE TITLE
Sequelize: Models, Migration, Seeder Files

### ISSUE THREAD

**Issue by surnan** [surnan/aircnc#3]
# Create Migration and Models for DB
##
### Tasks
- [x] Install all necessary packages to enable Sequelize and setup Sequelize environment
- [x] Users: Create migrations, model, seeder
- [x] Spots: Create migrations, model, seeder
- [ ] Bookings: Create migrations, model, seeder
- [ ] Reviews: Create migrations, model, seeder
- [ ] SpotImages: Create migrations, model, seeder
- [ ] ReviewImages: Create migrations, model, seeder

**Comment by surnan** [comment]
# Create Migration and Models for DB
##
### Tasks
- [x] Install all necessary packages to enable Sequelize and setup Sequelize environment
- [x] Users: Create migrations, model, seeder
- [x] Spots: Create migrations, model, seeder
- [ ] Bookings: Create migrations, model, seeder
- [ ] Reviews: Create migrations, model, seeder
- [ ] SpotImages: Create migrations, model, seeder
- [ ] ReviewImages: Create migrations, model, seeder
